% ERTRconds.m
%% setup 

colorps = [relevant_ps(:,strcmp(xname,'R')),relevant_ps(:,strcmp(xname,'O'))];
colorbs = [relevant_bs(:,strcmp(xname,'R')),relevant_bs(:,strcmp(xname,'O'))];
conds = struct(...
        'name',...
            {'Task-responsive','Neither','E[R]-only','T[R]-only','Both','E[R]','Non-E[R]','T[R]','Non-T[R]'},...
        'color',...
            {[0 0 0],[0 0 0],[1 0 0],[0 0 1],[1 0 1],[248, 118, 109]/256,0.5*[1 1 1],[109, 118, 248]/256,0.5*[1 1 1]},...
        'thisalluok',...
            {this_allu_ok,...
            this_allu_ok & ~any(colorps<sigthresh,2),...
            this_allu_ok & colorps(:,1)<sigthresh & ~(colorps(:,2)<sigthresh),...
            this_allu_ok & ~(colorps(:,1)<sigthresh) & colorps(:,2)<sigthresh,...
            this_allu_ok & all(colorps<sigthresh,2),...
            this_allu_ok & colorps(:,1)<sigthresh,...
            this_allu_ok & ~(colorps(:,1)<sigthresh),...
            this_allu_ok & colorps(:,2)<sigthresh,...
            this_allu_ok & ~(colorps(:,2)<sigthresh)...
            });
condn = arrayfun(@(x)sum(x.thisalluok),conds);
xn = {'R','E[R]';'O','T[R]'}; attri=1;
lgtxt = {['neither (p>' num2str(sigthresh) ')'],[xn{1,2} '-only'],[xn{2,2} '-only'],'both'};
colorxpypxy = {relevant_ps(this_allu_ok,strcmp(xname,xn{1,1})),relevant_ps(this_allu_ok,strcmp(xname,xn{2,1})),[],[]};
ertr_conds = conds;

